title: Example site for the Stravaig Theme
description: This is an example site for the Stravaig theme. It is intended to show how
    the theme can be used and what it looks like.

exclude:
  - scripts

kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

github:
  repository_url: https://github.com/Stravaig-Projects/stravaig-theme

nuget:
  # url: https://www.nuget.org/packages/Stravaig.Gedcom
  urls:
    # - https://www.nuget.org/packages/Stravaig.Configuration.Diagnostics.Core
    # - https://www.nuget.org/packages/Stravaig.Configuration.Diagnostics.Logging
    - https://www.nuget.org/packages/Stravaig.Configuration.Diagnostics.Serilog